FROM php:7.4.12-fpm
LABEL maintainer="liujiawen.personal@outlook.com"
COPY ./php.sh /php.sh
RUN chmod +x /php.sh && /php.sh
RUN rm -rf /php.sh
# 解决容器内外权限不一致的问题
# RUN usermod -u 1001 www-data && groupmod -g 1001 www-data
