version: "2"
services:
  php:
    build:
      context: ./php
      dockerfile: ./php/dockerfile
    container_name: php
    restart: on-failure:5
    mem_limit: 1024m
    volumes:
      - /var/www:/var/www
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure:5
    mem_limit: 1024m
    volumes:
      - /var/www/conf/docker-mysql/my.cnf:/etc/mysql/my.cnf:rw
      - /var/www/logs/docker-mysql:/var/log/mysql
      # - /var/www/data/docker-mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis:5.0
    container_name: redis
    restart: on-failure:5
    mem_limit: 1024m
    volumes:
      # - /var/www/conf/docker-redis/redis.conf:/etc/redis/redis.conf:rw
      # - /var/www/data/docker-redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx/dockerfile
    container_name: nginx
    restart: on-failure:5
    mem_limit: 1024m
    volumes:
      - /var/www:/var/www
      # - /var/www/conf/docker-nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      # - /var/www/conf/docker-nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host