# NOTE: <https://docs.docker.com/compose/compose-file/compose-file-v3/>
version: "2"
services:
  php:
    build:
      context: php
    #   dockerfile: ./php/dockerfile
    container_name: php
    restart: on-failure:5
    mem_limit: 256m
    # NOTE: version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256m
    working_dir: /var/www
    user: 1000:1000
    volumes:
      - /home/susy/MyWork:/var/www
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure:5
    mem_limit: 512m
    # NOTE: version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512m
    volumes:
      - /home/susy/MyWork/conf/docker-mysql:/etc/mysql:rw
      - /home/susy/MyWork/logs/docker-mysql:/var/log/mysql:rw
      - /home/susy/MyWork/data/docker-mysql:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "localhost"
  redis:
    image: redis:5.0
    container_name: redis
    restart: on-failure:5
    mem_limit: 256m
    # NOTE: version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256m
    command: redis-server /etc/redis/redis.conf --protected-mode yes
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
      - /home/susy/MyWork/data/docker-redis:/data:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure:5
    mem_limit: 256m
    # NOTE: version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256m
    volumes:
      - /home/susy/MyWork:/var/www:rw
      - /home/susy/MyWork/conf/docker-nginx:/etc/nginx:rw
      - /home/susy/MyWork/logs/docker-nginx:/var/log/nginx/:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host